services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672  # AMQP port
      - 15672:15672  # Management UI port
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
    environment:
      RABBITMQ_DEFAULT_USER: omsa4code
      RABBITMQ_DEFAULT_PASS: omsa4code


networks:
  rabbitmq_go_net:
    driver: bridge
